<a href="https://colab.research.google.com/github/AFynjy/AFynjy.gifthub.io/blob/master/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

1.Создание и вывод массива 

функция linspace создаёт массив, первые 2 числа это начало и конец диапазона, в котором находятся значения массива. 3 число - кол-во элементов массива.

In [18]:
a=np.linspace(10,20,21)
print(a)

[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20. ]


2.Создаём массив, вычисляем поэлементно косинусы и синусы. Возводим в квадрат и складываем. С помощью функции np.all проверяем, что в ответе только единицы.

In [68]:
b=np.linspace(-2*np.pi,2*np.pi,5)
print(b)

[-6.28318531 -3.14159265  0.          3.14159265  6.28318531]


In [71]:
c=np.sin(b).astype(int)
d=np.cos(b)
e=np.square(c)
f=np.square(d)
sumkv=e+f
print(c)
print(d)
print(e)
print(f)
print(sumkv)
print(np.all(sumkv))



[0 0 0 0 0]
[ 1. -1.  1. -1.  1.]
[0 0 0 0 0]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
True


3. Создаём 2 матрицы находим сумму поэлементно, а также с помощью функции dot перемнажаем их.

In [77]:
k=np.array([[-3, 4], 
            [4, 3]])
l=np.array([[2, 1], 
            [1, 2]])
sumkl=k+l
print(sumkl)

L = k.dot(l)
K = l.dot(k)

print(L)
print(K)


[[-1  5]
 [ 5  5]]
[[-2  5]
 [11 10]]
[[-2 11]
 [ 5 10]]


In [102]:
y=np.array([1,2,3,4,5])
anew=np.array([3,2,1,0,-1])
RSS=np.square(y-anew)
print(RSS)
print('RSS = ', RSS.sum())

[ 4  0  4 16 36]
RSS =  60


4.Так как у нас матрицы размерами 1x5 и 1x3 нам необходимо транспонировать одну из матриц, чтобы мы смогли перемножить их. Выполним оба способа поочереди.

In [105]:
matr=np.matrix('4 1 34 1 3')
Matr=np.matrix('12 112 1')
matrNew=matr.transpose()
newMatrix=matrNew.dot(Matr)
print(newMatrix)
# DS=matr*Matr
# print(DS)

[[  48  448    4]
 [  12  112    1]
 [ 408 3808   34]
 [  12  112    1]
 [  36  336    3]]


In [106]:
matrnew=Matr.transpose()
newmatrix=matrnew.dot(matr)
print(newmatrix)

[[  48   12  408   12   36]
 [ 448  112 3808  112  336]
 [   4    1   34    1    3]]
